import { vi } from 'vitest';
import type { AppContainer } from '../../src/main/container';

type DeepPartial<T> = {
  [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

function deepMerge<T extends Record<string, unknown>>(
  target: T,
  source: DeepPartial<T>,
): T {
  const result = { ...target };
  for (const key of Object.keys(source) as Array<keyof T>) {
    const sourceVal = source[key];
    const targetVal = target[key];
    if (
      sourceVal !== null &&
      sourceVal !== undefined &&
      typeof sourceVal === 'object' &&
      !Array.isArray(sourceVal) &&
      typeof targetVal === 'object' &&
      targetVal !== null &&
      !Array.isArray(targetVal)
    ) {
      result[key] = deepMerge(
        targetVal as Record<string, unknown>,
        sourceVal as Record<string, unknown>,
      ) as T[keyof T];
    } else if (sourceVal !== undefined) {
      result[key] = sourceVal as T[keyof T];
    }
  }
  return result;
}

export function createMockContainer(
  overrides: DeepPartial<AppContainer> = {},
): AppContainer {
  const defaultJwt = {
    verify: vi.fn(),
    signAccessToken: vi.fn(),
  };

  const defaultTenantRepo = {
    findById: vi.fn().mockResolvedValue({ isActive: () => true }),
  };

  const base: AppContainer = {
    prisma: {} as AppContainer['prisma'],
    auditService: { log: vi.fn() } as unknown as AppContainer['auditService'],
    auth: {
      loginUseCase: { execute: vi.fn() },
      refreshTokenUseCase: { execute: vi.fn() },
      logoutUseCase: { execute: vi.fn() },
      getMeUseCase: { execute: vi.fn() },
      changePasswordUseCase: { execute: vi.fn() },
      revokeSessionUseCase: { execute: vi.fn() },
      setupTotpUseCase: { execute: vi.fn() },
      confirmTotpUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['auth'],
    tenant: {
      createTenantUseCase: { execute: vi.fn() },
      getTenantUseCase: { execute: vi.fn() },
      listTenantsUseCase: { execute: vi.fn() },
      updateTenantUseCase: { execute: vi.fn() },
      activateTenantUseCase: { execute: vi.fn() },
      deactivateTenantUseCase: { execute: vi.fn() },
      createBranchUseCase: { execute: vi.fn() },
      getBranchUseCase: { execute: vi.fn() },
      listBranchesUseCase: { execute: vi.fn() },
      updateBranchUseCase: { execute: vi.fn() },
      deactivateBranchUseCase: { execute: vi.fn() },
      activateBranchUseCase: { execute: vi.fn() },
      generateLogoUploadUrlUseCase: { execute: vi.fn() },
      confirmLogoUploadUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['tenant'],
    user: {
      createUserUseCase: { execute: vi.fn() },
      getUserUseCase: { execute: vi.fn() },
      listUsersUseCase: { execute: vi.fn() },
      updateUserUseCase: { execute: vi.fn() },
      deactivateUserUseCase: { execute: vi.fn() },
      unlockUserUseCase: { execute: vi.fn() },
      resetUserPasswordUseCase: { execute: vi.fn() },
      inviteUserUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['user'],
    property: {
      createPropertyUseCase: { execute: vi.fn() },
      getPropertyUseCase: { execute: vi.fn() },
      listPropertiesUseCase: { execute: vi.fn() },
      updatePropertyUseCase: { execute: vi.fn() },
      deletePropertyUseCase: { execute: vi.fn() },
      geocodePropertyUseCase: { execute: vi.fn() },
      searchAddressesUseCase: { execute: vi.fn() },
      importPropertiesUseCase: { execute: vi.fn() },
      getPropertyImportStatusUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['property'],
    serviceType: {
      createServiceTypeUseCase: { execute: vi.fn() },
      getServiceTypeUseCase: { execute: vi.fn() },
      listServiceTypesUseCase: { execute: vi.fn() },
      updateServiceTypeUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['serviceType'],
    pricingRule: {
      createPricingRuleUseCase: { execute: vi.fn() },
      listPricingRulesUseCase: { execute: vi.fn() },
      updatePricingRuleUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['pricingRule'],
    inspector: {
      createInspectorUseCase: { execute: vi.fn() },
      getInspectorUseCase: { execute: vi.fn() },
      listInspectorsUseCase: { execute: vi.fn() },
      updateInspectorUseCase: { execute: vi.fn() },
      createAvailabilitySlotUseCase: { execute: vi.fn() },
      listAvailabilitySlotsUseCase: { execute: vi.fn() },
      updateAvailabilitySlotUseCase: { execute: vi.fn() },
      linkInspectorToUserUseCase: { execute: vi.fn() },
      deactivateInspectorUseCase: { execute: vi.fn() },
      generateInspectorPhotoUploadUrlUseCase: { execute: vi.fn() },
      confirmInspectorPhotoUploadUseCase: { execute: vi.fn() },
      updateInspectorSelfProfileUseCase: { execute: vi.fn() },
      generateInspectorDocumentUploadUrlUseCase: { execute: vi.fn() },
      confirmInspectorDocumentUploadUseCase: { execute: vi.fn() },
      getInspectorDocumentDownloadUrlUseCase: { execute: vi.fn() },
      getInspectorAvailabilityTemplateUseCase: { execute: vi.fn() },
      updateInspectorAvailabilityTemplateUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
      slotRepo: { findByIdAny: vi.fn() },
    } as AppContainer['inspector'],
    appointment: {
      createAppointmentUseCase: { execute: vi.fn() },
      getAppointmentUseCase: { execute: vi.fn() },
      listAppointmentsUseCase: { execute: vi.fn() },
      updateAppointmentUseCase: { execute: vi.fn() },
      executeStatusTransitionUseCase: { execute: vi.fn() },
      performCrossCheckUseCase: { execute: vi.fn() },
      forceManualConfirmationUseCase: { execute: vi.fn() },
      importAppointmentsUseCase: { execute: vi.fn() },
      getImportStatusUseCase: { execute: vi.fn() },
      deleteAppointmentUseCase: { execute: vi.fn() },
      bulkEditAppointmentsUseCase: { execute: vi.fn() },
      bulkResendReminderUseCase: { execute: vi.fn() },
      bulkCancelAppointmentsUseCase: { execute: vi.fn() },
      bulkRescheduleAppointmentsUseCase: { execute: vi.fn() },
      bulkStatusTransitionUseCase: { execute: vi.fn() },
      bulkAssignInspectorUseCase: { execute: vi.fn() },
      bulkReopenForRescheduleUseCase: { execute: vi.fn() },
      reopenForRescheduleUseCase: { execute: vi.fn() },
      appointmentRepo: { findContactById: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['appointment'],
    audit: {
      listAuditLogsUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['audit'],
    serviceGroup: {
      createServiceGroupUseCase: { execute: vi.fn() },
      getServiceGroupUseCase: { execute: vi.fn() },
      listServiceGroupsUseCase: { execute: vi.fn() },
      publishServiceGroupUseCase: { execute: vi.fn() },
      assignInspectorManuallyUseCase: { execute: vi.fn() },
      cancelServiceGroupUseCase: { execute: vi.fn() },
      addAppointmentsToGroupUseCase: { execute: vi.fn() },
      checkAppointmentsEligibilityForGroupUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['serviceGroup'],
    marketplace: {
      getMarketplaceOffersUseCase: { execute: vi.fn() },
      acceptOfferUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['marketplace'],
    tenantPortal: {
      getPortalDataUseCase: { execute: vi.fn() },
      confirmAppointmentUseCase: { execute: vi.fn() },
      rescheduleRequestUseCase: { execute: vi.fn() },
      updateContactUseCase: { execute: vi.fn() },
      reportUnavailabilityUseCase: { execute: vi.fn() },
      generatePortalTokenUseCase: { execute: vi.fn() },
      tokenRepo: {
        findByTokenHash: vi.fn(),
        findActiveByAppointmentId: vi.fn(),
        save: vi.fn(),
        revokeAndSave: vi.fn(),
        updateStatus: vi.fn(),
        updateLastAccessedAt: vi.fn(),
        revokeAllForAppointment: vi.fn(),
      },
      tokenService: { generateRawToken: vi.fn(), hashToken: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['tenantPortal'],
    inspectorExecution: {
      getInspectorScheduleUseCase: { execute: vi.fn() },
      getAppointmentDetailUseCase: { execute: vi.fn() },
      startInspectionUseCase: { execute: vi.fn() },
      finishInspectionUseCase: { execute: vi.fn() },
      saveExecutionProgressUseCase: { execute: vi.fn() },
      reopenExecutionUseCase: { execute: vi.fn() },
      requestAssetUploadUseCase: { execute: vi.fn() },
      confirmAssetUploadUseCase: { execute: vi.fn() },
      getMarketplaceOffersUseCase: { execute: vi.fn() },
      draftInspectorInvoiceUseCase: { execute: vi.fn() },
      listAppointmentAssetsUseCase: { execute: vi.fn() },
      getAppointmentAssetDownloadUrlUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['inspectorExecution'],
    billing: {
      createFinancialEntriesOnDoneUseCase: { execute: vi.fn() },
      getFinancialSummaryUseCase: { execute: vi.fn() },
      listFinancialEntriesUseCase: { execute: vi.fn() },
      getFinancialEntryUseCase: { execute: vi.fn() },
      approveFinancialEntryUseCase: { execute: vi.fn() },
      cancelFinancialEntryUseCase: { execute: vi.fn() },
      createManualAdjustmentUseCase: { execute: vi.fn() },
      createRefundUseCase: { execute: vi.fn() },
      generateInvoiceUseCase: { execute: vi.fn() },
      listInvoicesUseCase: { execute: vi.fn() },
      getInvoiceUseCase: { execute: vi.fn() },
      downloadInvoiceUseCase: { execute: vi.fn() },
      markInvoicePaidUseCase: { execute: vi.fn() },
      batchMarkInvoicesPaidUseCase: { execute: vi.fn() },
      reverseInvoicePaymentUseCase: { execute: vi.fn() },
      getReconciliationSummaryUseCase: { execute: vi.fn() },
      voidFinancialEntryUseCase: { execute: vi.fn() },
      generateTenantInvoiceUseCase: { execute: vi.fn() },
      regenerateInspectorInvoiceUseCase: { execute: vi.fn() },
      regenerateTenantInvoiceUseCase: { execute: vi.fn() },
      listTenantInvoicesUseCase: { execute: vi.fn() },
      approveDraftInvoiceUseCase: { execute: vi.fn() },
      rejectDraftInvoiceUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['billing'],
    report: {
      requestReportUseCase: { execute: vi.fn() },
      getReportStatusUseCase: { execute: vi.fn() },
      downloadReportUseCase: { execute: vi.fn() },
      listReportsUseCase: { execute: vi.fn() },
      processReportJobUseCase: { execute: vi.fn() },
      createScheduledReportUseCase: { execute: vi.fn() },
      listScheduledReportsUseCase: { execute: vi.fn() },
      // Feature 019
      getScheduledReportUseCase: { execute: vi.fn() },
      updateScheduledReportUseCase: { execute: vi.fn() },
      pauseScheduledReportUseCase: { execute: vi.fn() },
      resumeScheduledReportUseCase: { execute: vi.fn() },
      deleteScheduledReportUseCase: { execute: vi.fn() },
      reassignScheduleOwnershipUseCase: { execute: vi.fn() },
      listScheduleRunsUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['report'],
    notification: {
      sendNotificationUseCase: { execute: vi.fn() },
      retryNotificationUseCase: { execute: vi.fn() },
      handleProviderWebhookUseCase: { execute: vi.fn() },
      listNotificationsUseCase: { execute: vi.fn() },
      getNotificationUseCase: { execute: vi.fn() },
      upsertNotificationTemplateUseCase: { execute: vi.fn() },
      listNotificationTemplatesUseCase: { execute: vi.fn() },
      createNotificationUseCase: { execute: vi.fn() },
      pollRetryableNotificationsUseCase: { execute: vi.fn() },
      dispatchRemindersUseCase: { execute: vi.fn() },
      dispatchEscalationsUseCase: { execute: vi.fn() },
      // Feature 018
      processUnsubscribeUseCase: { execute: vi.fn() },
      renderUnsubscribePageUseCase: { execute: vi.fn() },
      listConsentsByRecipientUseCase: { execute: vi.fn() },
      overrideConsentUseCase: { execute: vi.fn() },
      reOptInUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
      webhookSignatureValidator: {
        validateResend: vi.fn().mockReturnValue(true),
      },
      mobileMessageWebhookToken: undefined,
    } as AppContainer['notification'],
    dashboard: {
      getDashboardStatsUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['dashboard'],
    appointmentTimeSlot: {
      createAppointmentTimeSlotUseCase: { execute: vi.fn() },
      updateAppointmentTimeSlotUseCase: { execute: vi.fn() },
      listAppointmentTimeSlotsUseCase: { execute: vi.fn() },
      listEffectiveTimeSlotsUseCase: { execute: vi.fn() },
      deleteAppointmentTimeSlotUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['appointmentTimeSlot'],
    serviceRegion: {
      createServiceRegionUseCase: { execute: vi.fn() },
      updateServiceRegionUseCase: { execute: vi.fn() },
      getServiceRegionUseCase: { execute: vi.fn() },
      listServiceRegionsUseCase: { execute: vi.fn() },
      deactivateServiceRegionUseCase: { execute: vi.fn() },
      deleteServiceRegionUseCase: { execute: vi.fn() },
      resolveRegionsUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['serviceRegion'],
    contact: {
      createContactUseCase: { execute: vi.fn() },
      updateContactUseCase: { execute: vi.fn() },
      getContactUseCase: { execute: vi.fn() },
      listContactsUseCase: { execute: vi.fn() },
      jwtService: { ...defaultJwt },
      tenantRepo: { ...defaultTenantRepo },
    } as AppContainer['contact'],
    cleanupSessionsWorker: { execute: vi.fn() } as AppContainer['cleanupSessionsWorker'],
    expireFilesWorker: { execute: vi.fn() } as AppContainer['expireFilesWorker'],
    geocodeWorker: { execute: vi.fn() } as AppContainer['geocodeWorker'],
    propertyImportWorker: { execute: vi.fn() } as AppContainer['propertyImportWorker'],
    appointmentImportWorker: { execute: vi.fn() } as AppContainer['appointmentImportWorker'],
    generateInvoiceFileWorker: { execute: vi.fn() } as AppContainer['generateInvoiceFileWorker'],
    expireTokensWorker: { execute: vi.fn() } as AppContainer['expireTokensWorker'],
    expireAssetsWorker: { execute: vi.fn() } as AppContainer['expireAssetsWorker'],
    notifyStuckInspectionsWorker: { execute: vi.fn() } as AppContainer['notifyStuckInspectionsWorker'],
    geocodeRetryWorker: { execute: vi.fn() } as AppContainer['geocodeRetryWorker'],
    keyExpiryCheckWorker: { execute: vi.fn() } as AppContainer['keyExpiryCheckWorker'],
    processSchedulesWorker: { execute: vi.fn() } as AppContainer['processSchedulesWorker'],
    expirePriorityWorker: { execute: vi.fn() } as AppContainer['expirePriorityWorker'],
    auditRetentionWorker: { execute: vi.fn() } as AppContainer['auditRetentionWorker'],
  };

  return deepMerge(base, overrides as DeepPartial<Record<string, unknown>>) as unknown as AppContainer;
}
