import type { AuthContext, InspectorInvoiceStatus } from '@properfy/shared';
import type { IInspectorInvoiceRepository } from '../../domain/inspector-invoice.repository';
import type { IFinancialEntryRepository } from '../../domain/financial-entry.repository';
import { InvoiceNotFoundError, InvoiceNotRegenerableError } from '../../domain/billing.errors';
import type { AuthorizationService } from '../../../../shared/domain/authorization.service';
import type { IJobQueue } from '../../../../shared/domain/job-queue';
import type { AuditService } from '../../../../shared/infrastructure/audit';

export interface RegenerateInspectorInvoiceInput {
  invoiceId: string;
  reason?: string;
  actor: AuthContext;
}

export interface RegenerateInspectorInvoiceOutput {
  id: string;
  inspectorId: string;
  periodStart: string;
  periodEnd: string;
  periodType: string;
  status: InspectorInvoiceStatus;
  totalAmount: number;
  currency: string;
  fileKey: string | null;
  previousInvoiceId: string | null;
  generatedByUserId: string | null;
  generatedAt: string | null;
  paidAt: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
}

export class RegenerateInspectorInvoiceUseCase {
  constructor(
    private readonly invoiceRepo: IInspectorInvoiceRepository,
    private readonly financialEntryRepo: IFinancialEntryRepository,
    private readonly auditService: AuditService,
    private readonly authorizationService: AuthorizationService,
    private readonly jobQueue?: IJobQueue,
  ) {}

  async execute(input: RegenerateInspectorInvoiceInput): Promise<RegenerateInspectorInvoiceOutput> {
    const { invoiceId, reason, actor } = input;

    // 1. Require a non-blank reason (sensitive financial operation)
    if (!reason?.trim()) {
      const { DomainError } = await import('../../../../shared/domain/errors');
      throw new DomainError('INVOICE_REGENERATION_REASON_REQUIRED', 'A reason is required to regenerate an invoice', 422);
    }

    // 2. Validate role - AM only
    this.authorizationService.assertRoles(actor, ['AM'], { action: 'financial.regenerate_invoice', entityType: 'InspectorInvoice' });

    // 3. Load existing invoice
    const existing = await this.invoiceRepo.findById(invoiceId);
    if (!existing) {
      throw new InvoiceNotFoundError();
    }

    // 4. Validate status is CLOSED or PAID
    if (!existing.canBeRegenerated()) {
      throw new InvoiceNotRegenerableError();
    }

    // 5. Recalculate totals from current approved entries
    const totalAmount = await this.financialEntryRepo.sumApprovedPayoutsForInspectorInPeriod(
      existing.inspectorId,
      existing.periodStart,
      endOfDay(existing.periodEnd),
    );

    // 6. Update invoice in-place (single atomic write — avoids @@unique collision)
    const now = new Date();
    await this.invoiceRepo.update(invoiceId, {
      status: 'CLOSED',
      totalAmount,
      generatedByUserId: actor.userId,
      generatedAt: now,
      notes: reason ?? null,
      fileKey: null,          // reset file — will be regenerated by the job
    });

    // 7. Audit log
    this.auditService.log({
      action: 'invoice.regenerated',
      actorType: 'USER',
      actorId: actor.userId,
      entityType: 'InspectorInvoice',
      entityId: invoiceId,       // same id — in-place
      reason,
      before: {
        previousInvoiceId: existing.previousInvoiceId,
        previousTotalAmount: Number(existing.totalAmount),
        previousStatus: existing.status,
      },
      after: {
        status: 'CLOSED',
        totalAmount: Number(totalAmount),
        currency: existing.currency,
      },
    });

    // 8. Enqueue file generation
    if (this.jobQueue) {
      await this.jobQueue.enqueue('billing.generate-invoice-file', { invoiceId });   // same id
    }

    return {
      id: invoiceId,
      inspectorId: existing.inspectorId,
      periodStart: formatDate(existing.periodStart),
      periodEnd: formatDate(existing.periodEnd),
      periodType: existing.periodType,
      status: 'CLOSED',
      totalAmount: Number(totalAmount),
      currency: existing.currency,
      fileKey: null,
      previousInvoiceId: existing.previousInvoiceId,  // preserved
      generatedByUserId: actor.userId,
      generatedAt: now.toISOString(),
      paidAt: null,
      notes: reason ?? null,
      createdAt: existing.createdAt.toISOString(),
      updatedAt: now.toISOString(),
    };
  }
}

function endOfDay(value: Date): Date {
  const end = new Date(value);
  end.setUTCHours(23, 59, 59, 999);
  return end;
}

function formatDate(value: Date): string {
  return value.toISOString().slice(0, 10);
}
