-- Allow platform-scoped notifications: notifications.tenant_id becomes nullable.
--
-- Not every notification belongs to an agency. The self-service forgot-password
-- flow emails AM, OP and INSP users, and those users have users.tenant_id NULL.
-- request-password-reset.use-case.ts worked around the NOT NULL constraint by
-- passing the literal string 'platform', which is not a tenants.id, so every
-- insert failed notifications_tenant_id_fkey (P2003) and POST /v1/auth/forgot-password
-- returned 500. Self-service password reset has therefore never worked for any
-- user without a tenant.
--
-- The fix stores NULL for platform-scoped notifications, mirroring
-- notification_templates.tenant_id, which has been nullable since
-- 20260316170908_add_notifications_and_templates precisely so platform defaults can
-- exist alongside per-agency overrides. Same semantics here: NULL means "the
-- platform owns this row", not "unknown".
--
-- The foreign key and the tenant_id index are unaffected. A NULL foreign-key value
-- is exempt from the FK check (MATCH SIMPLE), and Postgres btree indexes do include
-- NULLs, so `WHERE tenant_id IS NULL` stays index-backed.
--
-- Expand-only and backward compatible: no existing row changes, and every caller
-- that still writes a real tenant id keeps working. Revert is
-- `ALTER TABLE "notifications" ALTER COLUMN "tenant_id" SET NOT NULL;`, which is
-- only safe while no NULL rows exist.

-- AlterTable
ALTER TABLE "notifications" ALTER COLUMN "tenant_id" DROP NOT NULL;
