-- v1 baseline — squash of the 124 pre-v1.0.0 migrations (2026-08).
-- Generated by replaying the full migration history into a clean PostGIS
-- container and diffing the result (prisma migrate diff --from-empty --to-url),
-- then appending what the differ cannot express:
--   * CREATE EXTENSION statements (prisma migrate diff never emits them);
--   * the reference rows that survive a clean replay (retention configs,
--     PII field mappings, platform notification templates) — platform config
--     every environment needs, production included.
-- Verified by replay-diff: old-history DB vs baseline DB produce an empty
-- prisma migrate diff and identical data dumps.
-- Pre-existing environments were baselined with `prisma migrate resolve`.

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- CreateEnum
CREATE TYPE "AppointmentContactRole" AS ENUM ('RENTAL_TENANT', 'RENTAL_TENANT_REPRESENTATIVE', 'HOUSEKEEPER', 'PROPERTY_MANAGER', 'BROKER', 'OTHER');

-- CreateEnum
CREATE TYPE "AppointmentStatus" AS ENUM ('DRAFT', 'AWAITING_INSPECTOR', 'SCHEDULED', 'DONE', 'CANCELLED', 'REJECTED');

-- CreateEnum
CREATE TYPE "AuditActorType" AS ENUM ('USER', 'SYSTEM', 'ANONYMOUS');

-- CreateEnum
CREATE TYPE "AuditRedactionStatus" AS ENUM ('NONE', 'PARTIAL', 'FULL', 'IN_PROGRESS');

-- CreateEnum
CREATE TYPE "AuditRetentionCategory" AS ENUM ('FINANCIAL', 'OPERATIONAL_CRITICAL', 'OPERATIONAL_GENERAL');

-- CreateEnum
CREATE TYPE "AvailabilitySlotStatus" AS ENUM ('AVAILABLE', 'BOOKED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "BillingPeriodType" AS ENUM ('WEEKLY', 'FORTNIGHTLY', 'MONTHLY');

-- CreateEnum
CREATE TYPE "BranchStatus" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "ConsentChangeSource" AS ENUM ('operator_override', 're_opt_in');

-- CreateEnum
CREATE TYPE "ContactChannelType" AS ENUM ('EMAIL', 'PHONE');

-- CreateEnum
CREATE TYPE "ContactType" AS ENUM ('RENTAL_TENANT', 'PROPERTY_MANAGER', 'HOUSEKEEPER', 'BROKER', 'OTHER');

-- CreateEnum
CREATE TYPE "CycleConfirmationSource" AS ENUM ('RENTAL_TENANT_PORTAL', 'OPERATOR_FORCED', 'RENTAL_TENANT_RESCHEDULE');

-- CreateEnum
CREATE TYPE "CycleInvalidatedReason" AS ENUM ('DATE_CHANGED', 'TIME_CHANGED', 'APPOINTMENT_REOPENED', 'RENTAL_TENANT_RESCHEDULE');

-- CreateEnum
CREATE TYPE "CycleStatus" AS ENUM ('PENDING', 'CONFIRMED', 'UNAVAILABLE', 'SUPERSEDED');

-- CreateEnum
CREATE TYPE "ErasureRequestStatus" AS ENUM ('PENDING', 'SCANNING', 'PREVIEW', 'CONFIRMED', 'EXECUTING', 'COMPLETED', 'FAILED');

-- CreateEnum
CREATE TYPE "FinancialEntryStatus" AS ENUM ('PENDING', 'APPROVED', 'CANCELLED', 'VOIDED');

-- CreateEnum
CREATE TYPE "FinancialEntryType" AS ENUM ('TENANT_DEBIT', 'INSPECTOR_PAYOUT', 'REFUND', 'MANUAL_ADJUSTMENT');

-- CreateEnum
CREATE TYPE "GeocodingStatus" AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'MANUAL');

-- CreateEnum
CREATE TYPE "InspectorInvoiceStatus" AS ENUM ('PENDING_REVIEW', 'CLOSED', 'PAID', 'VOID');

-- CreateEnum
CREATE TYPE "InspectorStatus" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "NotificationAttemptStatus" AS ENUM ('PENDING', 'SUCCESS', 'FAILED');

-- CreateEnum
CREATE TYPE "NotificationChannel" AS ENUM ('EMAIL', 'SMS');

-- CreateEnum
CREATE TYPE "NotificationClass" AS ENUM ('TRANSACTIONAL', 'OPERATIONAL', 'MARKETING');

-- CreateEnum
CREATE TYPE "NotificationStatus" AS ENUM ('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'SKIPPED', 'SKIPPED_OPT_OUT');

-- CreateEnum
CREATE TYPE "PayoutType" AS ENUM ('FIXED', 'PERCENTAGE');

-- CreateEnum
CREATE TYPE "PreservationRuleType" AS ENUM ('CROSS_CHECK', 'LEGAL_HOLD');

-- CreateEnum
CREATE TYPE "PriceRuleStatus" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "PropertyType" AS ENUM ('APARTMENT', 'HOUSE');

-- CreateEnum
CREATE TYPE "RegionStatus" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "RentalTenantConfirmationStatus" AS ENUM ('PENDING', 'CONFIRMED', 'UNAVAILABLE', 'NO_RESPONSE');

-- CreateEnum
CREATE TYPE "RentalTenantPortalAction" AS ENUM ('VIEW', 'CONFIRM', 'RESCHEDULE', 'CONTACT_UPDATED', 'UNAVAILABLE_REPORTED', 'GROUP_JOIN', 'SURVEY_SUBMITTED');

-- CreateEnum
CREATE TYPE "RentalTenantPortalTokenStatus" AS ENUM ('ACTIVE', 'EXPIRED', 'REVOKED', 'SUPERSEDED');

-- CreateEnum
CREATE TYPE "ReportStatus" AS ENUM ('PENDING', 'PROCESSING', 'READY', 'FAILED');

-- CreateEnum
CREATE TYPE "ReportType" AS ENUM ('APPOINTMENTS', 'FINANCIAL', 'PERFORMANCE', 'AGENCIES');

-- CreateEnum
CREATE TYPE "RestrictionSource" AS ENUM ('RENTAL_TENANT_PORTAL', 'OPERATOR', 'IMPORT');

-- CreateEnum
CREATE TYPE "ServiceGroupStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ACCEPTED', 'CANCELLED', 'REJECTED');

-- CreateEnum
CREATE TYPE "ServiceTypeFlowType" AS ENUM ('ROUTINE', 'INGOING', 'OUTGOING');

-- CreateEnum
CREATE TYPE "ServiceTypeStatus" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "TenantStatus" AS ENUM ('PENDING', 'ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('AM', 'OP', 'CL_ADMIN', 'CL_USER', 'INSP');

-- CreateEnum
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'LOCKED', 'PENDING_INVITE');

-- CreateTable
CREATE TABLE "api_keys" (
    "id" TEXT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "key_hash" VARCHAR(64) NOT NULL,
    "prefix" VARCHAR(20) NOT NULL,
    "role" VARCHAR(10) NOT NULL,
    "scopes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "expires_at" TIMESTAMP(3),
    "revoked_at" TIMESTAMP(3),
    "last_used_at" TIMESTAMP(3),
    "created_by_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "api_keys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app_credentials" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "username" VARCHAR(200) NOT NULL,
    "password_encrypted" TEXT NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "app_url" VARCHAR(1000),
    "branch_id" TEXT,
    "instructions_password_encrypted" TEXT,
    "instructions_url" VARCHAR(1000),
    "needs_auth_code" BOOLEAN NOT NULL DEFAULT false,
    "is_default" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "app_credentials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "appointment_app_credentials" (
    "id" TEXT NOT NULL,
    "appointment_id" TEXT NOT NULL,
    "app_credential_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "appointment_app_credentials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "appointment_confirmation_cycles" (
    "id" TEXT NOT NULL,
    "appointment_id" TEXT NOT NULL,
    "cycle_number" INTEGER NOT NULL,
    "scheduled_date" DATE NOT NULL,
    "time_slot" TEXT,
    "status" "CycleStatus" NOT NULL DEFAULT 'PENDING',
    "confirmation_source" "CycleConfirmationSource",
    "confirmed_at" TIMESTAMP(3),
    "invalidated_at" TIMESTAMP(3),
    "invalidated_reason" "CycleInvalidatedReason",
    "portal_token_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "appointment_confirmation_cycles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "appointment_contacts" (
    "id" TEXT NOT NULL,
    "appointment_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "contact_id" TEXT,
    "role" "AppointmentContactRole" NOT NULL DEFAULT 'RENTAL_TENANT',
    "is_primary" BOOLEAN NOT NULL DEFAULT true,
    "snapshot_name" VARCHAR(200) NOT NULL,
    "snapshot_email" VARCHAR(254),
    "snapshot_phone" VARCHAR(30),

    CONSTRAINT "appointment_contacts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "appointment_imports" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    "file_key" VARCHAR(500) NOT NULL,
    "original_filename" VARCHAR(255) NOT NULL,
    "total_rows" INTEGER NOT NULL DEFAULT 0,
    "success_count" INTEGER NOT NULL DEFAULT 0,
    "error_count" INTEGER NOT NULL DEFAULT 0,
    "errors_json" JSONB,
    "created_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "branch_id" TEXT,
    "preview_json" JSONB,
    "results_json" JSONB,

    CONSTRAINT "appointment_imports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "appointment_restrictions" (
    "id" TEXT NOT NULL,
    "appointment_id" TEXT NOT NULL,
    "is_home" BOOLEAN NOT NULL,
    "unavailable_days_json" JSONB,
    "unavailable_hours_json" JSONB,
    "notes" TEXT,
    "source" "RestrictionSource" NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "available_slots_json" JSONB,

    CONSTRAINT "appointment_restrictions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "appointments" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "branch_id" TEXT NOT NULL,
    "property_id" TEXT NOT NULL,
    "service_type_id" TEXT NOT NULL,
    "inspector_id" TEXT,
    "status" "AppointmentStatus" NOT NULL DEFAULT 'DRAFT',
    "scheduled_date" DATE NOT NULL,
    "key_required" BOOLEAN NOT NULL DEFAULT false,
    "meeting_location" VARCHAR(500),
    "key_location" VARCHAR(500),
    "rental_tenant_confirmation_status" "RentalTenantConfirmationStatus" NOT NULL DEFAULT 'PENDING',
    "price_amount" DECIMAL(12,2) NOT NULL,
    "payout_amount" DECIMAL(12,2) NOT NULL,
    "pricing_rule_snapshot_json" JSONB NOT NULL,
    "notes" TEXT,
    "custom_fields_json" JSONB,
    "reason" TEXT,
    "created_by_user_id" TEXT NOT NULL,
    "done_checked_by_user_id" TEXT,
    "done_checked_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "service_group_id" TEXT,
    "cancellation_reason_code" VARCHAR(50),
    "rejection_reason_code" VARCHAR(50),
    "appointment_number" SERIAL NOT NULL,
    "done_marked_by_user_id" TEXT,
    "rental_tenant_note" TEXT,
    "active_confirmation_cycle_id" TEXT,
    "observation" TEXT,
    "time_slot_start" VARCHAR(5) NOT NULL,
    "time_slot_end" VARCHAR(5) NOT NULL,

    CONSTRAINT "appointments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_legal_holds" (
    "id" TEXT NOT NULL,
    "entity_type" VARCHAR(100) NOT NULL,
    "entity_id" TEXT NOT NULL,
    "tenant_id" TEXT,
    "reason" TEXT NOT NULL,
    "placed_by_user_id" TEXT NOT NULL,
    "placed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "released_by_user_id" TEXT,
    "released_at" TIMESTAMP(3),
    "is_active" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "audit_legal_holds_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT,
    "actor_type" "AuditActorType" NOT NULL,
    "actor_id" TEXT,
    "entity_type" VARCHAR(100) NOT NULL,
    "entity_id" TEXT,
    "action" VARCHAR(200) NOT NULL,
    "reason" TEXT,
    "before_json" JSONB,
    "after_json" JSONB,
    "request_id" VARCHAR(100),
    "ip_address" VARCHAR(45),
    "metadata_json" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "retention_category" "AuditRetentionCategory",
    "redaction_status" "AuditRedactionStatus" NOT NULL DEFAULT 'NONE',
    "cold_storage" BOOLEAN NOT NULL DEFAULT false,
    "preservation_rule_id" TEXT,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_logs_archive" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT,
    "actor_type" "AuditActorType" NOT NULL,
    "actor_id" TEXT,
    "entity_type" VARCHAR(100) NOT NULL,
    "entity_id" TEXT,
    "action" VARCHAR(200) NOT NULL,
    "reason" TEXT,
    "before_json" JSONB,
    "after_json" JSONB,
    "request_id" VARCHAR(100),
    "ip_address" VARCHAR(45),
    "metadata_json" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL,
    "retention_category" "AuditRetentionCategory",
    "redaction_status" "AuditRedactionStatus" NOT NULL DEFAULT 'NONE',
    "cold_storage" BOOLEAN NOT NULL DEFAULT true,
    "preservation_rule_id" TEXT,
    "archived_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_archive_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_preservation_rules" (
    "id" TEXT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "rule_type" "PreservationRuleType" NOT NULL,
    "entity_type" VARCHAR(100),
    "entity_id" TEXT,
    "tenant_id" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "audit_preservation_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "audit_retention_category_configs" (
    "id" TEXT NOT NULL,
    "name" "AuditRetentionCategory" NOT NULL,
    "retention_years" INTEGER NOT NULL,
    "hard_delete_enabled" BOOLEAN NOT NULL DEFAULT false,
    "description" TEXT,
    "action_patterns_json" JSONB NOT NULL DEFAULT '[]',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "audit_retention_category_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "branches" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "address_json" JSONB,
    "status" "BranchStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "contact_email" VARCHAR(254),

    CONSTRAINT "branches_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "contacts" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT,
    "type" "ContactType" NOT NULL,
    "display_name" VARCHAR(200) NOT NULL,
    "company" VARCHAR(200),
    "primary_email" VARCHAR(254),
    "primary_phone" VARCHAR(30),
    "additional_channels_json" JSONB NOT NULL DEFAULT '[]',
    "notes" TEXT,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "contacts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "cron_job_runs" (
    "job_name" VARCHAR(100) NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "local_date" DATE NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "cron_job_runs_pkey" PRIMARY KEY ("job_name","tenant_id","local_date")
);

-- CreateTable
CREATE TABLE "data_subject_erasure_requests" (
    "id" TEXT NOT NULL,
    "subject_identifier_type" VARCHAR(20) NOT NULL,
    "subject_identifier_value" VARCHAR(500) NOT NULL,
    "resolved_pii_values_json" JSONB,
    "status" "ErasureRequestStatus" NOT NULL DEFAULT 'PENDING',
    "entries_found_count" INTEGER,
    "entries_redacted_count" INTEGER,
    "entries_flagged_for_review_count" INTEGER,
    "completion_report_json" JSONB,
    "initiated_by_user_id" TEXT NOT NULL,
    "initiated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMP(3),

    CONSTRAINT "data_subject_erasure_requests_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "financial_entries" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "appointment_id" TEXT,
    "inspector_id" TEXT,
    "entry_type" "FinancialEntryType" NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "currency" CHAR(3) NOT NULL,
    "status" "FinancialEntryStatus" NOT NULL DEFAULT 'PENDING',
    "description" VARCHAR(500) NOT NULL,
    "effective_at" TIMESTAMP(3) NOT NULL,
    "initiated_by_user_id" TEXT NOT NULL,
    "approved_by_user_id" TEXT,
    "approved_at" TIMESTAMP(3),
    "reference_entry_id" TEXT,
    "reason" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "voided_by_user_id" TEXT,
    "voided_at" TIMESTAMP(3),
    "void_reason" TEXT,

    CONSTRAINT "financial_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "idempotency_keys" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "response" JSONB NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "payload_hash" VARCHAR(64),

    CONSTRAINT "idempotency_keys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "inspection_executions" (
    "id" TEXT NOT NULL,
    "appointment_id" TEXT NOT NULL,
    "inspector_id" TEXT NOT NULL,
    "started_at" TIMESTAMP(3) NOT NULL,
    "finished_at" TIMESTAMP(3),
    "start_latitude" DECIMAL(10,7) NOT NULL,
    "start_longitude" DECIMAL(10,7) NOT NULL,
    "finish_latitude" DECIMAL(10,7),
    "finish_longitude" DECIMAL(10,7),
    "checklist_json" JSONB,
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "geolocation_distance_meters" DECIMAL(10,2),
    "resumed_at" TIMESTAMP(3),

    CONSTRAINT "inspection_executions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "inspector_availability_slots" (
    "id" TEXT NOT NULL,
    "inspector_id" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "start_time" VARCHAR(5) NOT NULL,
    "end_time" VARCHAR(5) NOT NULL,
    "region_json" JSONB,
    "capacity" INTEGER NOT NULL DEFAULT 1,
    "status" "AvailabilitySlotStatus" NOT NULL DEFAULT 'AVAILABLE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "is_operator_override" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "inspector_availability_slots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "inspector_invoices" (
    "id" TEXT NOT NULL,
    "inspector_id" TEXT NOT NULL,
    "period_start" DATE NOT NULL,
    "period_end" DATE NOT NULL,
    "period_type" "BillingPeriodType" NOT NULL,
    "status" "InspectorInvoiceStatus" NOT NULL,
    "total_amount" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "currency" CHAR(3) NOT NULL,
    "file_key" TEXT,
    "generated_by_user_id" TEXT,
    "issued_at" TIMESTAMP(3),
    "paid_at" TIMESTAMP(3),
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "paid_by_user_id" TEXT,
    "payment_reference" VARCHAR(255),
    "drafted_by_inspector_id" TEXT,
    "invoice_number" INTEGER,
    "inspector_name" TEXT,
    "line_items_snapshot" JSONB,
    "inspector_abn" VARCHAR(20),

    CONSTRAINT "inspector_invoices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "inspector_regions" (
    "inspector_id" TEXT NOT NULL,
    "region_id" TEXT NOT NULL,
    "assigned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assigned_by" TEXT,

    CONSTRAINT "inspector_regions_pkey" PRIMARY KEY ("inspector_id","region_id")
);

-- CreateTable
CREATE TABLE "inspectors" (
    "id" TEXT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "email" VARCHAR(254) NOT NULL,
    "phone" VARCHAR(20),
    "status" "InspectorStatus" NOT NULL DEFAULT 'ACTIVE',
    "payment_settings_json" JSONB NOT NULL DEFAULT '{}',
    "service_types_json" JSONB NOT NULL DEFAULT '[]',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "user_id" TEXT,
    "full_name" VARCHAR(300),
    "address" JSONB,
    "abn" VARCHAR(20),
    "date_of_birth" DATE,
    "insurance_file_key" TEXT,
    "insurance_expires_at" DATE,
    "police_check_file_key" TEXT,
    "police_check_expires_at" DATE,
    "blocked_clients_json" JSONB NOT NULL DEFAULT '[]',
    "photo_storage_key" TEXT,
    "insurance_meta_json" JSONB,
    "police_check_meta_json" JSONB,
    "availability_template_json" JSONB NOT NULL DEFAULT '{}',
    "billing_cycle" "BillingPeriodType",

    CONSTRAINT "inspectors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "integration_settings" (
    "id" TEXT NOT NULL,
    "provider" VARCHAR(50) NOT NULL,
    "encrypted_config" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "updated_by_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "integration_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_attempts" (
    "id" TEXT NOT NULL,
    "notification_id" TEXT NOT NULL,
    "attempt_number" INTEGER NOT NULL,
    "status" "NotificationAttemptStatus" NOT NULL DEFAULT 'PENDING',
    "provider_error" TEXT,
    "started_at" TIMESTAMP(3) NOT NULL,
    "finished_at" TIMESTAMP(3),

    CONSTRAINT "notification_attempts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_consents" (
    "id" TEXT NOT NULL,
    "recipient" VARCHAR(320) NOT NULL,
    "channel" "NotificationChannel" NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "opted_out" BOOLEAN NOT NULL DEFAULT false,
    "opted_out_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "notification_class" "NotificationClass" NOT NULL DEFAULT 'OPERATIONAL',
    "change_source" "ConsentChangeSource",
    "changed_at" TIMESTAMP(3),
    "changed_by_user_id" TEXT,
    "reason" TEXT,

    CONSTRAINT "notification_consents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notification_templates" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT,
    "template_code" VARCHAR(100) NOT NULL,
    "channel" "NotificationChannel" NOT NULL,
    "subject" VARCHAR(255),
    "body_html" TEXT,
    "body_text" TEXT NOT NULL,
    "variables_json" JSONB NOT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "notification_class" "NotificationClass" NOT NULL DEFAULT 'OPERATIONAL',

    CONSTRAINT "notification_templates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "notifications" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT,
    "appointment_id" TEXT,
    "recipient" VARCHAR(320) NOT NULL,
    "channel" "NotificationChannel" NOT NULL,
    "template_code" VARCHAR(100) NOT NULL,
    "status" "NotificationStatus" NOT NULL DEFAULT 'PENDING',
    "provider_name" VARCHAR(50),
    "provider_message_id" VARCHAR(200),
    "sent_at" TIMESTAMP(3),
    "delivered_at" TIMESTAMP(3),
    "failed_at" TIMESTAMP(3),
    "failure_reason" TEXT,
    "payload_json" JSONB NOT NULL,
    "retry_count" INTEGER NOT NULL DEFAULT 0,
    "next_retry_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "notification_class" "NotificationClass",

    CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "password_history" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "password_history_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "password_reset_tokens" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "used_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pii_field_mappings" (
    "id" TEXT NOT NULL,
    "action_pattern" VARCHAR(200) NOT NULL,
    "json_field_path" VARCHAR(500) NOT NULL,
    "classification" VARCHAR(50) NOT NULL,
    "requires_manual_review" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "pii_field_mappings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "properties" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "branch_id" TEXT,
    "property_code" VARCHAR(50) NOT NULL,
    "type" "PropertyType" NOT NULL,
    "street" VARCHAR(300) NOT NULL,
    "address_line_2" VARCHAR(200),
    "suburb" VARCHAR(100) NOT NULL,
    "postcode" VARCHAR(20) NOT NULL,
    "state" VARCHAR(100) NOT NULL,
    "country" VARCHAR(100) NOT NULL DEFAULT 'AU',
    "lat" DECIMAL(10,7),
    "lng" DECIMAL(10,7),
    "geocoding_status" "GeocodingStatus" NOT NULL DEFAULT 'PENDING',
    "notes" TEXT,
    "rules_json" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "coordinates" geometry,
    "normalized_address_key" VARCHAR(750) NOT NULL DEFAULT '',
    "private_area_m2" DECIMAL(10,2),
    "total_area_m2" DECIMAL(10,2),
    "furnished" BOOLEAN,
    "linen_provided" BOOLEAN,
    "rent_amount" DECIMAL(12,2),
    "apartment_number" VARCHAR(50),
    "property_number" INTEGER,

    CONSTRAINT "properties_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rental_tenant_portal_activities" (
    "id" TEXT NOT NULL,
    "appointment_id" TEXT NOT NULL,
    "rental_tenant_portal_token_id" TEXT NOT NULL,
    "action" "RentalTenantPortalAction" NOT NULL,
    "previous_values_json" JSONB,
    "new_values_json" JSONB,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "retention_category" "AuditRetentionCategory",
    "redaction_status" "AuditRedactionStatus" NOT NULL DEFAULT 'NONE',
    "cold_storage" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "tenant_portal_activities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rental_tenant_portal_activities_archive" (
    "id" TEXT NOT NULL,
    "appointment_id" TEXT NOT NULL,
    "rental_tenant_portal_token_id" TEXT NOT NULL,
    "action" "RentalTenantPortalAction" NOT NULL,
    "previous_values_json" JSONB,
    "new_values_json" JSONB,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL,
    "retention_category" "AuditRetentionCategory",
    "redaction_status" "AuditRedactionStatus" NOT NULL DEFAULT 'NONE',
    "cold_storage" BOOLEAN NOT NULL DEFAULT true,
    "archived_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tenant_portal_activities_archive_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rental_tenant_portal_tokens" (
    "id" TEXT NOT NULL,
    "appointment_id" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "status" "RentalTenantPortalTokenStatus" NOT NULL DEFAULT 'ACTIVE',
    "last_accessed_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "used_at" TIMESTAMP(3),
    "raw_token_encrypted" TEXT,
    "confirmation_cycle_id" TEXT,
    "confirm_cutoff_at" TIMESTAMP(3),

    CONSTRAINT "tenant_portal_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reports" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT,
    "report_type" "ReportType" NOT NULL,
    "filters_json" JSONB NOT NULL,
    "status" "ReportStatus" NOT NULL DEFAULT 'PENDING',
    "file_key" TEXT,
    "requested_by_user_id" TEXT NOT NULL,
    "started_at" TIMESTAMP(3),
    "completed_at" TIMESTAMP(3),
    "failed_at" TIMESTAMP(3),
    "error_message" TEXT,
    "row_count" INTEGER,
    "expires_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "agency_scoped" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "reports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "satisfaction_surveys" (
    "id" TEXT NOT NULL,
    "appointment_id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "inspector_id" TEXT NOT NULL,
    "rating" INTEGER NOT NULL,
    "comment" TEXT,
    "submitted_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "satisfaction_surveys_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_groups" (
    "id" TEXT NOT NULL,
    "service_type_id" TEXT NOT NULL,
    "status" "ServiceGroupStatus" NOT NULL DEFAULT 'DRAFT',
    "offered_count" INTEGER NOT NULL DEFAULT 0,
    "confirmed_count" INTEGER NOT NULL DEFAULT 0,
    "scheduled_date" DATE NOT NULL,
    "time_window" VARCHAR(11) NOT NULL,
    "assigned_inspector_id" TEXT,
    "published_at" TIMESTAMP(3),
    "assigned_at" TIMESTAMP(3),
    "created_by_user_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "region_name" VARCHAR(255),
    "description" TEXT,
    "service_region_id" TEXT,
    "group_number" SERIAL NOT NULL,

    CONSTRAINT "service_groups_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_price_rules" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "service_type_id" TEXT NOT NULL,
    "branch_id" TEXT,
    "price_amount" DECIMAL(12,2) NOT NULL,
    "payout_type" "PayoutType" NOT NULL,
    "payout_value" DECIMAL(12,2) NOT NULL,
    "bonus_rule_json" JSONB,
    "status" "PriceRuleStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "currency" VARCHAR(3) NOT NULL,

    CONSTRAINT "service_price_rules_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_regions" (
    "id" TEXT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "status" "RegionStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "geom" geometry,
    "geojson" JSONB NOT NULL DEFAULT '{}',
    "color" VARCHAR(20) NOT NULL DEFAULT '#3b82f6',
    "created_by_user_id" TEXT,
    "tenant_id" TEXT,
    "region_number" SERIAL NOT NULL,

    CONSTRAINT "service_regions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_types" (
    "id" TEXT NOT NULL,
    "code" VARCHAR(50) NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "flow_type" "ServiceTypeFlowType" NOT NULL,
    "requires_rental_tenant_confirmation" BOOLEAN NOT NULL DEFAULT true,
    "status" "ServiceTypeStatus" NOT NULL DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "service_types_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "refresh_token_hash" TEXT NOT NULL,
    "ip_address" VARCHAR(45),
    "user_agent" VARCHAR(500),
    "expires_at" TIMESTAMP(3) NOT NULL,
    "revoked_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "country_code" VARCHAR(2),
    "device_fingerprint" VARCHAR(64),

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tenants" (
    "id" TEXT NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "legal_name" VARCHAR(200) NOT NULL,
    "status" "TenantStatus" NOT NULL DEFAULT 'PENDING',
    "timezone" VARCHAR(60) NOT NULL DEFAULT 'Australia/Sydney',
    "currency" CHAR(3) NOT NULL DEFAULT 'AUD',
    "settings_json" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "appointment_code_prefix" VARCHAR(4),

    CONSTRAINT "tenants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT,
    "branch_id" TEXT,
    "role" "UserRole" NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "email" VARCHAR(254) NOT NULL,
    "phone" VARCHAR(20),
    "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',
    "password_hash" TEXT NOT NULL,
    "totp_secret" TEXT,
    "totp_enabled" BOOLEAN NOT NULL DEFAULT false,
    "failed_login_count" INTEGER NOT NULL DEFAULT 0,
    "locked_until" TIMESTAMP(3),
    "last_login_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "timezone" VARCHAR(60),

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "api_keys_key_hash_key" ON "api_keys"("key_hash" ASC);

-- CreateIndex
CREATE INDEX "api_keys_revoked_at_idx" ON "api_keys"("revoked_at" ASC);

-- CreateIndex
CREATE INDEX "app_credentials_tenant_id_branch_id_idx" ON "app_credentials"("tenant_id" ASC, "branch_id" ASC);

-- CreateIndex
CREATE INDEX "app_credentials_tenant_id_is_active_idx" ON "app_credentials"("tenant_id" ASC, "is_active" ASC);

-- CreateIndex
CREATE INDEX "app_credentials_tenant_id_is_default_idx" ON "app_credentials"("tenant_id" ASC, "is_default" ASC);

-- CreateIndex
CREATE INDEX "app_credentials_tenant_id_name_idx" ON "app_credentials"("tenant_id" ASC, "name" ASC);

-- CreateIndex
CREATE INDEX "appointment_app_credentials_app_credential_id_idx" ON "appointment_app_credentials"("app_credential_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "appointment_app_credentials_appointment_id_app_credential_i_key" ON "appointment_app_credentials"("appointment_id" ASC, "app_credential_id" ASC);

-- CreateIndex
CREATE INDEX "appointment_app_credentials_appointment_id_idx" ON "appointment_app_credentials"("appointment_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "appointment_confirmation_cycles_appointment_id_cycle_number_key" ON "appointment_confirmation_cycles"("appointment_id" ASC, "cycle_number" ASC);

-- CreateIndex
CREATE INDEX "appointment_confirmation_cycles_appointment_id_status_idx" ON "appointment_confirmation_cycles"("appointment_id" ASC, "status" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "appointment_confirmation_cycles_portal_token_id_key" ON "appointment_confirmation_cycles"("portal_token_id" ASC);

-- CreateIndex
CREATE INDEX "appointment_contacts_appointment_id_idx" ON "appointment_contacts"("appointment_id" ASC);

-- CreateIndex
CREATE INDEX "appointment_contacts_contact_id_idx" ON "appointment_contacts"("contact_id" ASC);

-- CreateIndex
CREATE INDEX "appointment_imports_created_at_idx" ON "appointment_imports"("created_at" ASC);

-- CreateIndex
CREATE INDEX "appointment_imports_created_by_user_id_idx" ON "appointment_imports"("created_by_user_id" ASC);

-- CreateIndex
CREATE INDEX "appointment_imports_status_idx" ON "appointment_imports"("status" ASC);

-- CreateIndex
CREATE INDEX "appointment_imports_tenant_id_idx" ON "appointment_imports"("tenant_id" ASC);

-- CreateIndex
CREATE INDEX "appointment_restrictions_appointment_id_idx" ON "appointment_restrictions"("appointment_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "appointments_appointment_number_key" ON "appointments"("appointment_number" ASC);

-- CreateIndex
CREATE INDEX "appointments_inspector_id_status_idx" ON "appointments"("inspector_id" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "appointments_scheduled_date_inspector_id_idx" ON "appointments"("scheduled_date" ASC, "inspector_id" ASC);

-- CreateIndex
CREATE INDEX "appointments_service_group_id_idx" ON "appointments"("service_group_id" ASC);

-- CreateIndex
CREATE INDEX "appointments_status_created_at_idx" ON "appointments"("status" ASC, "created_at" ASC);

-- CreateIndex
CREATE INDEX "appointments_tenant_id_branch_id_idx" ON "appointments"("tenant_id" ASC, "branch_id" ASC);

-- CreateIndex
CREATE INDEX "appointments_tenant_id_inspector_id_idx" ON "appointments"("tenant_id" ASC, "inspector_id" ASC);

-- CreateIndex
CREATE INDEX "appointments_tenant_id_scheduled_date_idx" ON "appointments"("tenant_id" ASC, "scheduled_date" ASC);

-- CreateIndex
CREATE INDEX "appointments_tenant_id_service_type_id_idx" ON "appointments"("tenant_id" ASC, "service_type_id" ASC);

-- CreateIndex
CREATE INDEX "appointments_tenant_id_status_idx" ON "appointments"("tenant_id" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "audit_legal_holds_entity_type_entity_id_is_active_idx" ON "audit_legal_holds"("entity_type" ASC, "entity_id" ASC, "is_active" ASC);

-- CreateIndex
CREATE INDEX "audit_legal_holds_tenant_id_idx" ON "audit_legal_holds"("tenant_id" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_action_idx" ON "audit_logs"("action" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_actor_id_idx" ON "audit_logs"("actor_id" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_created_at_idx" ON "audit_logs"("created_at" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_entity_type_entity_id_idx" ON "audit_logs"("entity_type" ASC, "entity_id" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_redaction_status_idx" ON "audit_logs"("redaction_status" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_retention_category_created_at_idx" ON "audit_logs"("retention_category" ASC, "created_at" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_tenant_id_idx" ON "audit_logs"("tenant_id" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_archive_action_idx" ON "audit_logs_archive"("action" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_archive_actor_id_idx" ON "audit_logs_archive"("actor_id" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_archive_archived_at_idx" ON "audit_logs_archive"("archived_at" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_archive_created_at_idx" ON "audit_logs_archive"("created_at" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_archive_entity_type_entity_id_idx" ON "audit_logs_archive"("entity_type" ASC, "entity_id" ASC);

-- CreateIndex
CREATE INDEX "audit_logs_archive_tenant_id_idx" ON "audit_logs_archive"("tenant_id" ASC);

-- CreateIndex
CREATE INDEX "audit_preservation_rules_entity_type_entity_id_idx" ON "audit_preservation_rules"("entity_type" ASC, "entity_id" ASC);

-- CreateIndex
CREATE INDEX "audit_preservation_rules_rule_type_is_active_idx" ON "audit_preservation_rules"("rule_type" ASC, "is_active" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "audit_retention_category_configs_name_key" ON "audit_retention_category_configs"("name" ASC);

-- CreateIndex
CREATE INDEX "branches_tenant_id_idx" ON "branches"("tenant_id" ASC);

-- CreateIndex
CREATE INDEX "branches_tenant_id_name_idx" ON "branches"("tenant_id" ASC, "name" ASC);

-- CreateIndex
CREATE INDEX "branches_tenant_id_status_idx" ON "branches"("tenant_id" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "contacts_display_name_trgm_idx" ON "contacts" USING GIN ("display_name" gin_trgm_ops);

-- CreateIndex
CREATE INDEX "contacts_tenant_id_display_name_idx" ON "contacts"("tenant_id" ASC, "display_name" ASC);

-- CreateIndex
CREATE INDEX "contacts_tenant_id_is_active_idx" ON "contacts"("tenant_id" ASC, "is_active" ASC);

-- CreateIndex
CREATE INDEX "contacts_tenant_id_type_idx" ON "contacts"("tenant_id" ASC, "type" ASC);

-- CreateIndex
CREATE INDEX "data_subject_erasure_requests_initiated_by_user_id_idx" ON "data_subject_erasure_requests"("initiated_by_user_id" ASC);

-- CreateIndex
CREATE INDEX "data_subject_erasure_requests_status_idx" ON "data_subject_erasure_requests"("status" ASC);

-- CreateIndex
CREATE INDEX "financial_entries_appointment_id_idx" ON "financial_entries"("appointment_id" ASC);

-- CreateIndex
CREATE INDEX "financial_entries_effective_at_idx" ON "financial_entries"("effective_at" ASC);

-- CreateIndex
CREATE INDEX "financial_entries_entry_type_idx" ON "financial_entries"("entry_type" ASC);

-- CreateIndex
CREATE INDEX "financial_entries_inspector_id_idx" ON "financial_entries"("inspector_id" ASC);

-- CreateIndex
CREATE INDEX "financial_entries_status_idx" ON "financial_entries"("status" ASC);

-- CreateIndex
CREATE INDEX "financial_entries_tenant_id_entry_type_status_idx" ON "financial_entries"("tenant_id" ASC, "entry_type" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "financial_entries_tenant_id_idx" ON "financial_entries"("tenant_id" ASC);

-- CreateIndex
CREATE INDEX "idempotency_keys_expires_at_idx" ON "idempotency_keys"("expires_at" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "idempotency_keys_key_key" ON "idempotency_keys"("key" ASC);

-- CreateIndex
CREATE INDEX "idempotency_keys_key_scope_idx" ON "idempotency_keys"("key" ASC, "scope" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "inspection_executions_appointment_id_key" ON "inspection_executions"("appointment_id" ASC);

-- CreateIndex
CREATE INDEX "inspection_executions_inspector_id_idx" ON "inspection_executions"("inspector_id" ASC);

-- CreateIndex
CREATE INDEX "inspection_executions_started_at_idx" ON "inspection_executions"("started_at" ASC);

-- CreateIndex
CREATE INDEX "inspector_availability_slots_inspector_id_date_idx" ON "inspector_availability_slots"("inspector_id" ASC, "date" ASC);

-- CreateIndex
CREATE INDEX "inspector_availability_slots_inspector_id_idx" ON "inspector_availability_slots"("inspector_id" ASC);

-- CreateIndex
CREATE INDEX "inspector_availability_slots_inspector_id_status_idx" ON "inspector_availability_slots"("inspector_id" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "inspector_invoices_inspector_id_status_idx" ON "inspector_invoices"("inspector_id" ASC, "status" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "inspector_invoices_invoice_number_key" ON "inspector_invoices"("invoice_number" ASC);

-- CreateIndex
CREATE INDEX "inspector_invoices_line_items_snapshot_gin" ON "inspector_invoices" USING GIN ("line_items_snapshot" jsonb_path_ops);

-- CreateIndex
CREATE INDEX "inspector_invoices_period_start_period_end_idx" ON "inspector_invoices"("period_start" ASC, "period_end" ASC);

-- CreateIndex
CREATE INDEX "inspector_regions_region_id_idx" ON "inspector_regions"("region_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "inspectors_email_key" ON "inspectors"("email" ASC);

-- CreateIndex
CREATE INDEX "inspectors_insurance_expires_at_idx" ON "inspectors"("insurance_expires_at" ASC);

-- CreateIndex
CREATE INDEX "inspectors_police_check_expires_at_idx" ON "inspectors"("police_check_expires_at" ASC);

-- CreateIndex
CREATE INDEX "inspectors_status_idx" ON "inspectors"("status" ASC);

-- CreateIndex
CREATE INDEX "inspectors_user_id_idx" ON "inspectors"("user_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "inspectors_user_id_key" ON "inspectors"("user_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "integration_settings_provider_key" ON "integration_settings"("provider" ASC);

-- CreateIndex
CREATE INDEX "notification_attempts_notification_id_attempt_number_idx" ON "notification_attempts"("notification_id" ASC, "attempt_number" ASC);

-- CreateIndex
CREATE INDEX "notification_attempts_notification_id_idx" ON "notification_attempts"("notification_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "notification_consents_recipient_channel_tenant_id_notificat_key" ON "notification_consents"("recipient" ASC, "channel" ASC, "tenant_id" ASC, "notification_class" ASC);

-- CreateIndex
CREATE INDEX "notification_consents_tenant_id_idx" ON "notification_consents"("tenant_id" ASC);

-- CreateIndex
CREATE INDEX "notification_templates_template_code_channel_idx" ON "notification_templates"("template_code" ASC, "channel" ASC);

-- CreateIndex
CREATE INDEX "notification_templates_tenant_id_idx" ON "notification_templates"("tenant_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "notification_templates_tenant_id_template_code_channel_key" ON "notification_templates"("tenant_id" ASC, "template_code" ASC, "channel" ASC);

-- CreateIndex
CREATE INDEX "notifications_appointment_id_idx" ON "notifications"("appointment_id" ASC);

-- CreateIndex
CREATE INDEX "notifications_channel_status_sent_at_idx" ON "notifications"("channel" ASC, "status" ASC, "sent_at" ASC);

-- CreateIndex
CREATE INDEX "notifications_next_retry_at_idx" ON "notifications"("next_retry_at" ASC);

-- CreateIndex
CREATE INDEX "notifications_provider_message_id_idx" ON "notifications"("provider_message_id" ASC);

-- CreateIndex
CREATE INDEX "notifications_status_idx" ON "notifications"("status" ASC);

-- CreateIndex
CREATE INDEX "notifications_template_code_idx" ON "notifications"("template_code" ASC);

-- CreateIndex
CREATE INDEX "notifications_tenant_id_idx" ON "notifications"("tenant_id" ASC);

-- CreateIndex
CREATE INDEX "password_history_user_id_created_at_idx" ON "password_history"("user_id" ASC, "created_at" ASC);

-- CreateIndex
CREATE INDEX "password_history_user_id_idx" ON "password_history"("user_id" ASC);

-- CreateIndex
CREATE INDEX "password_reset_tokens_expires_at_idx" ON "password_reset_tokens"("expires_at" ASC);

-- CreateIndex
CREATE INDEX "password_reset_tokens_token_hash_idx" ON "password_reset_tokens"("token_hash" ASC);

-- CreateIndex
CREATE INDEX "password_reset_tokens_user_id_idx" ON "password_reset_tokens"("user_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "pii_field_mappings_action_pattern_json_field_path_key" ON "pii_field_mappings"("action_pattern" ASC, "json_field_path" ASC);

-- CreateIndex
CREATE INDEX "pii_field_mappings_classification_idx" ON "pii_field_mappings"("classification" ASC);

-- CreateIndex
CREATE INDEX "properties_branch_id_idx" ON "properties"("branch_id" ASC);

-- CreateIndex
CREATE INDEX "properties_coordinates_idx" ON "properties" USING GIST ("coordinates" gist_geometry_ops_2d);

-- CreateIndex
CREATE INDEX "properties_tenant_id_idx" ON "properties"("tenant_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "properties_tenant_id_property_code_key" ON "properties"("tenant_id" ASC, "property_code" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "properties_tenant_id_property_number_key" ON "properties"("tenant_id" ASC, "property_number" ASC);

-- CreateIndex
CREATE INDEX "properties_tenant_id_type_idx" ON "properties"("tenant_id" ASC, "type" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_activities_action_idx" ON "rental_tenant_portal_activities"("action" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_activities_appointment_id_idx" ON "rental_tenant_portal_activities"("appointment_id" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_activities_created_at_idx" ON "rental_tenant_portal_activities"("created_at" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_activities_redaction_status_idx" ON "rental_tenant_portal_activities"("redaction_status" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_activities_tenant_portal_token_id_idx" ON "rental_tenant_portal_activities"("rental_tenant_portal_token_id" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_activities_archive_action_idx" ON "rental_tenant_portal_activities_archive"("action" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_activities_archive_appointment_id_idx" ON "rental_tenant_portal_activities_archive"("appointment_id" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_activities_archive_archived_at_idx" ON "rental_tenant_portal_activities_archive"("archived_at" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_activities_archive_created_at_idx" ON "rental_tenant_portal_activities_archive"("created_at" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_activities_archive_tenant_portal_token_id_idx" ON "rental_tenant_portal_activities_archive"("rental_tenant_portal_token_id" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_tokens_appointment_id_idx" ON "rental_tenant_portal_tokens"("appointment_id" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_tokens_expires_at_idx" ON "rental_tenant_portal_tokens"("expires_at" ASC);

-- CreateIndex
CREATE INDEX "tenant_portal_tokens_status_idx" ON "rental_tenant_portal_tokens"("status" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "tenant_portal_tokens_token_hash_key" ON "rental_tenant_portal_tokens"("token_hash" ASC);

-- CreateIndex
CREATE INDEX "reports_created_at_idx" ON "reports"("created_at" ASC);

-- CreateIndex
CREATE INDEX "reports_expires_at_idx" ON "reports"("expires_at" ASC);

-- CreateIndex
CREATE INDEX "reports_report_type_idx" ON "reports"("report_type" ASC);

-- CreateIndex
CREATE INDEX "reports_requested_by_user_id_idx" ON "reports"("requested_by_user_id" ASC);

-- CreateIndex
CREATE INDEX "reports_status_idx" ON "reports"("status" ASC);

-- CreateIndex
CREATE INDEX "reports_tenant_id_idx" ON "reports"("tenant_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "satisfaction_surveys_appointment_id_key" ON "satisfaction_surveys"("appointment_id" ASC);

-- CreateIndex
CREATE INDEX "satisfaction_surveys_inspector_id_tenant_id_submitted_at_idx" ON "satisfaction_surveys"("inspector_id" ASC, "tenant_id" ASC, "submitted_at" DESC);

-- CreateIndex
CREATE INDEX "satisfaction_surveys_tenant_id_idx" ON "satisfaction_surveys"("tenant_id" ASC);

-- CreateIndex
CREATE INDEX "service_groups_assigned_inspector_id_idx" ON "service_groups"("assigned_inspector_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "service_groups_group_number_key" ON "service_groups"("group_number" ASC);

-- CreateIndex
CREATE INDEX "service_groups_scheduled_date_idx" ON "service_groups"("scheduled_date" ASC);

-- CreateIndex
CREATE INDEX "service_groups_service_region_id_idx" ON "service_groups"("service_region_id" ASC);

-- CreateIndex
CREATE INDEX "service_groups_status_idx" ON "service_groups"("status" ASC);

-- CreateIndex
CREATE INDEX "service_price_rules_branch_id_idx" ON "service_price_rules"("branch_id" ASC);

-- CreateIndex
CREATE INDEX "service_price_rules_service_type_id_idx" ON "service_price_rules"("service_type_id" ASC);

-- CreateIndex
CREATE INDEX "service_price_rules_tenant_id_idx" ON "service_price_rules"("tenant_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "service_price_rules_tenant_id_service_type_id_branch_id_key" ON "service_price_rules"("tenant_id" ASC, "service_type_id" ASC, "branch_id" ASC);

-- CreateIndex
CREATE INDEX "service_regions_geom_idx" ON "service_regions" USING GIST ("geom" gist_geometry_ops_2d);

-- CreateIndex
CREATE UNIQUE INDEX "service_regions_region_number_key" ON "service_regions"("region_number" ASC);

-- CreateIndex
CREATE INDEX "service_regions_status_idx" ON "service_regions"("status" ASC);

-- CreateIndex
CREATE INDEX "service_regions_tenant_id_idx" ON "service_regions"("tenant_id" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "service_regions_tenant_id_name_key" ON "service_regions"("tenant_id" ASC, "name" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "service_types_code_key" ON "service_types"("code" ASC);

-- CreateIndex
CREATE INDEX "service_types_status_idx" ON "service_types"("status" ASC);

-- CreateIndex
CREATE INDEX "sessions_expires_at_idx" ON "sessions"("expires_at" ASC);

-- CreateIndex
CREATE INDEX "sessions_refresh_token_hash_idx" ON "sessions"("refresh_token_hash" ASC);

-- CreateIndex
CREATE INDEX "sessions_user_id_idx" ON "sessions"("user_id" ASC);

-- CreateIndex
CREATE INDEX "sessions_user_id_revoked_at_idx" ON "sessions"("user_id" ASC, "revoked_at" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "tenants_appointment_code_prefix_key" ON "tenants"("appointment_code_prefix" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "tenants_legal_name_key" ON "tenants"("legal_name" ASC);

-- CreateIndex
CREATE INDEX "tenants_status_idx" ON "tenants"("status" ASC);

-- CreateIndex
CREATE INDEX "users_branch_id_idx" ON "users"("branch_id" ASC);

-- CreateIndex
CREATE INDEX "users_email_idx" ON "users"("email" ASC);

-- CreateIndex
CREATE INDEX "users_tenant_id_idx" ON "users"("tenant_id" ASC);

-- CreateIndex
CREATE INDEX "users_tenant_id_role_idx" ON "users"("tenant_id" ASC, "role" ASC);

-- CreateIndex
CREATE INDEX "users_tenant_id_status_idx" ON "users"("tenant_id" ASC, "status" ASC);

-- AddForeignKey
ALTER TABLE "app_credentials" ADD CONSTRAINT "app_credentials_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app_credentials" ADD CONSTRAINT "app_credentials_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_app_credentials" ADD CONSTRAINT "appointment_app_credentials_app_credential_id_fkey" FOREIGN KEY ("app_credential_id") REFERENCES "app_credentials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_app_credentials" ADD CONSTRAINT "appointment_app_credentials_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_confirmation_cycles" ADD CONSTRAINT "appointment_confirmation_cycles_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_confirmation_cycles" ADD CONSTRAINT "appointment_confirmation_cycles_portal_token_id_fkey" FOREIGN KEY ("portal_token_id") REFERENCES "rental_tenant_portal_tokens"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_contacts" ADD CONSTRAINT "appointment_contacts_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_contacts" ADD CONSTRAINT "appointment_contacts_contact_id_fkey" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_imports" ADD CONSTRAINT "appointment_imports_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_imports" ADD CONSTRAINT "appointment_imports_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_imports" ADD CONSTRAINT "appointment_imports_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_restrictions" ADD CONSTRAINT "appointment_restrictions_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_active_confirmation_cycle_id_fkey" FOREIGN KEY ("active_confirmation_cycle_id") REFERENCES "appointment_confirmation_cycles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_done_checked_by_user_id_fkey" FOREIGN KEY ("done_checked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_done_marked_by_user_id_fkey" FOREIGN KEY ("done_marked_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_inspector_id_fkey" FOREIGN KEY ("inspector_id") REFERENCES "inspectors"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "properties"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_service_group_id_fkey" FOREIGN KEY ("service_group_id") REFERENCES "service_groups"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_service_type_id_fkey" FOREIGN KEY ("service_type_id") REFERENCES "service_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_preservation_rule_id_fkey" FOREIGN KEY ("preservation_rule_id") REFERENCES "audit_preservation_rules"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "branches" ADD CONSTRAINT "branches_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "contacts" ADD CONSTRAINT "contacts_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "cron_job_runs" ADD CONSTRAINT "cron_job_runs_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "financial_entries" ADD CONSTRAINT "financial_entries_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "financial_entries" ADD CONSTRAINT "financial_entries_approved_by_user_id_fkey" FOREIGN KEY ("approved_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "financial_entries" ADD CONSTRAINT "financial_entries_initiated_by_user_id_fkey" FOREIGN KEY ("initiated_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "financial_entries" ADD CONSTRAINT "financial_entries_inspector_id_fkey" FOREIGN KEY ("inspector_id") REFERENCES "inspectors"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "financial_entries" ADD CONSTRAINT "financial_entries_reference_entry_id_fkey" FOREIGN KEY ("reference_entry_id") REFERENCES "financial_entries"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "financial_entries" ADD CONSTRAINT "financial_entries_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "financial_entries" ADD CONSTRAINT "financial_entries_voided_by_user_id_fkey" FOREIGN KEY ("voided_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inspection_executions" ADD CONSTRAINT "inspection_executions_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inspection_executions" ADD CONSTRAINT "inspection_executions_inspector_id_fkey" FOREIGN KEY ("inspector_id") REFERENCES "inspectors"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inspector_availability_slots" ADD CONSTRAINT "inspector_availability_slots_inspector_id_fkey" FOREIGN KEY ("inspector_id") REFERENCES "inspectors"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inspector_invoices" ADD CONSTRAINT "inspector_invoices_generated_by_user_id_fkey" FOREIGN KEY ("generated_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inspector_invoices" ADD CONSTRAINT "inspector_invoices_inspector_id_fkey" FOREIGN KEY ("inspector_id") REFERENCES "inspectors"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inspector_invoices" ADD CONSTRAINT "inspector_invoices_paid_by_user_id_fkey" FOREIGN KEY ("paid_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inspector_regions" ADD CONSTRAINT "inspector_regions_inspector_id_fkey" FOREIGN KEY ("inspector_id") REFERENCES "inspectors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inspector_regions" ADD CONSTRAINT "inspector_regions_region_id_fkey" FOREIGN KEY ("region_id") REFERENCES "service_regions"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "inspectors" ADD CONSTRAINT "inspectors_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_attempts" ADD CONSTRAINT "notification_attempts_notification_id_fkey" FOREIGN KEY ("notification_id") REFERENCES "notifications"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_consents" ADD CONSTRAINT "notification_consents_changed_by_user_id_fkey" FOREIGN KEY ("changed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notification_templates" ADD CONSTRAINT "notification_templates_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "password_history" ADD CONSTRAINT "password_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "password_reset_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "properties" ADD CONSTRAINT "properties_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "properties" ADD CONSTRAINT "properties_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rental_tenant_portal_activities" ADD CONSTRAINT "tenant_portal_activities_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rental_tenant_portal_activities" ADD CONSTRAINT "tenant_portal_activities_tenant_portal_token_id_fkey" FOREIGN KEY ("rental_tenant_portal_token_id") REFERENCES "rental_tenant_portal_tokens"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rental_tenant_portal_tokens" ADD CONSTRAINT "tenant_portal_tokens_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rental_tenant_portal_tokens" ADD CONSTRAINT "tenant_portal_tokens_confirmation_cycle_id_fkey" FOREIGN KEY ("confirmation_cycle_id") REFERENCES "appointment_confirmation_cycles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reports" ADD CONSTRAINT "reports_requested_by_user_id_fkey" FOREIGN KEY ("requested_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reports" ADD CONSTRAINT "reports_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "satisfaction_surveys" ADD CONSTRAINT "satisfaction_surveys_appointment_id_fkey" FOREIGN KEY ("appointment_id") REFERENCES "appointments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "satisfaction_surveys" ADD CONSTRAINT "satisfaction_surveys_inspector_id_fkey" FOREIGN KEY ("inspector_id") REFERENCES "inspectors"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "satisfaction_surveys" ADD CONSTRAINT "satisfaction_surveys_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_groups" ADD CONSTRAINT "service_groups_assigned_inspector_id_fkey" FOREIGN KEY ("assigned_inspector_id") REFERENCES "inspectors"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_groups" ADD CONSTRAINT "service_groups_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_groups" ADD CONSTRAINT "service_groups_service_region_id_fkey" FOREIGN KEY ("service_region_id") REFERENCES "service_regions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_groups" ADD CONSTRAINT "service_groups_service_type_id_fkey" FOREIGN KEY ("service_type_id") REFERENCES "service_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_price_rules" ADD CONSTRAINT "service_price_rules_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_price_rules" ADD CONSTRAINT "service_price_rules_service_type_id_fkey" FOREIGN KEY ("service_type_id") REFERENCES "service_types"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_price_rules" ADD CONSTRAINT "service_price_rules_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_regions" ADD CONSTRAINT "service_regions_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_regions" ADD CONSTRAINT "service_regions_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_branch_id_fkey" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE SET NULL ON UPDATE CASCADE;


-- Reference data (rows that survive a clean replay of the old history)
INSERT INTO audit_retention_category_configs VALUES ('b5b07c0f-b689-4590-9049-d86e46a2a8c8', 'FINANCIAL', 7, false, 'Financial / fiscal audit entries (billing, refund, invoice, manual adjustment). 7-year retention per Brazilian fiscal legislation.', '["financial.", "billing.", "invoice.", "refund.", "manualAdjustment."]', '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO audit_retention_category_configs VALUES ('ee0f1a19-9fac-4b5e-abc4-b861104f0ded', 'OPERATIONAL_CRITICAL', 5, false, 'Appointment status transitions, cross-check actions, user/inspector lifecycle, permission changes. 5-year retention per Brazilian Civil Code general prescription period.', '[]', '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO audit_retention_category_configs VALUES ('c60ef212-8f13-454f-bc62-1dc2b5ce6b09', 'OPERATIONAL_GENERAL', 2, false, 'Read access logs, auth success events, portal views. 2-year retention for high-volume low-value audit entries.', '["auth.loginSuccess", "auth.refreshToken", "auth.tokenVerified", "portal.view", "read."]', '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO notification_templates VALUES ('e764de77-3e8f-432e-9cc4-82a0f69afbaa', NULL, 'INSPECTION_CANCELLED_AGENCY', 'EMAIL', 'Inspection Cancelled - {{propertyAddress}}', '<p>The inspection {{appointmentCode}} at {{propertyAddress}} scheduled for {{scheduledDate}} has been cancelled.</p>', 'The inspection {{appointmentCode}} at {{propertyAddress}} scheduled for {{scheduledDate}} has been cancelled.', '["propertyAddress", "appointmentCode", "scheduledDate"]', true, '2026-08-06 13:10:23.422', '2026-08-06 13:10:23.422', 'TRANSACTIONAL');
INSERT INTO notification_templates VALUES ('0d16f1ed-dec6-4140-a63e-05077a98c84e', NULL, 'TENANT_NOTICE_FORWARDED_AGENCY', 'EMAIL', 'Tenant notice not sent - {{propertyAddress}}', '<p>Your agency contacts tenants directly, so Properfy did not send "{{suppressedTemplateLabel}}" for inspection {{appointmentCode}} at {{propertyAddress}} on {{scheduledDate}}. Please pass it on to the tenant.</p>', 'Your agency contacts tenants directly, so Properfy did not send "{{suppressedTemplateLabel}}" for inspection {{appointmentCode}} at {{propertyAddress}} on {{scheduledDate}}. Please pass it on to the tenant.', '["suppressedTemplateLabel", "suppressedChannel", "propertyAddress", "appointmentCode", "scheduledDate"]', true, '2026-08-06 13:10:23.428', '2026-08-06 13:10:23.428', 'TRANSACTIONAL');
INSERT INTO notification_templates VALUES ('e43f45b1-264d-47c5-ba7c-4c1d03f25c6b', NULL, 'INSPECTION_SATISFACTION_SURVEY', 'EMAIL', 'How did your inspection go?', '<p>Your inspection has been completed. Tell us how it went: <a href="{{surveyLink}}">Rate your inspection</a></p>', 'Your inspection has been completed. Tell us how it went: {{surveyLink}}', '["surveyLink"]', true, '2026-08-06 13:10:23.471', '2026-08-06 13:10:23.471', 'OPERATIONAL');
INSERT INTO pii_field_mappings VALUES ('0ecf0fb0-eb19-412b-b5bd-0d10420b3977', 'user.', 'email', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('369dcb76-1bc0-49f4-86bf-6f9a25d4978b', 'user.', 'phone', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('a2282546-a724-467d-8d5a-9a1c244f98de', 'user.', 'name', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('49a20ed9-0b5f-4c38-9ab3-304f361753d7', 'inspector.', 'email', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('9e9ff7bf-915d-4b0e-b189-7ebd685c5d21', 'inspector.', 'phone', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('2c966011-d40e-4b5b-ad99-8f12e872dad1', 'inspector.', 'name', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('2c8a2b1d-7dd3-42ec-bafb-85cfa6c05132', 'auth.', 'email', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('c1e0f7ad-2d8e-4f68-b553-ed1dcdf2bb97', 'auth.', 'phone', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('299260ad-b317-4898-9193-f2a9e7b61b0b', 'auth.', 'name', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('fa020d7a-4ee0-4cd6-9833-3cded251796a', 'portal.', 'primaryEmail', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('e344618c-fc59-46ae-b3f6-a35eb2a46b4b', 'portal.', 'primaryPhone', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('c2976924-6631-403b-aa11-ee5cb7386fdb', 'portal.', 'email', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('65283e88-1b4e-43cd-b48a-053afeb2678b', 'portal.', 'phone', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('0b3e4419-f954-4770-8e4a-d2afb2d47b9d', 'portal.', 'name', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('1c14c4a0-8cb4-4c5b-ac62-8cc65e197884', 'appointment.', 'contact.tenantName', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('20650849-64a1-4ae9-b335-61a1312ab0c1', 'appointment.', 'contact.primaryEmail', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('04ad90d0-1e29-42d3-932b-e1828feec7ca', 'appointment.', 'contact.primaryPhone', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('664821dc-e711-4aed-b9d5-b736c8cc4366', 'appointment.', 'tenantName', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('bd67efab-6707-40d4-9974-20d92ac2129a', 'appointment.', 'tenantEmail', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('38b5c1ec-c545-48ee-a64d-4cf094a78886', 'appointment.', 'tenantPhone', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('232affe0-1a29-4faa-ac3c-550c1421974d', 'inspector.', 'paymentSettingsJson', 'sensitive_financial', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('1ee78a93-546f-4004-b56a-58e2b797ba37', 'appointment.status_transition', 'metadata.inspectorName', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('65883941-5678-4611-8ddb-699f55cfe0b1', 'appointment.', 'customFieldsJson', 'unstructured', true, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('4192c216-1f53-4ca8-97df-dad760203f39', 'portal.', 'secondaryEmail', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
INSERT INTO pii_field_mappings VALUES ('663008bd-206a-45da-bbc1-a6cd80ec51ca', 'portal.', 'secondaryPhone', 'direct', false, '2026-08-06 13:10:22.617', '2026-08-06 13:10:22.617');
